# Generated by Django 5.2 on 2026-09-14 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_payment_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paymentRefrenceID',
            field=models.TextField(null=True),
        ),
    ]
