# Generated by Django 5.2 on 2026-09-14 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_payment_paymentrefrenceid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='paymentRefrenceID',
            new_name='gatewayReferenceID',
        ),
    ]
