# Generated by Django 5.2 on 2026-09-14 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_rename_paymentrefrenceid_payment_gatewayreferenceid'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sellerId', models.IntegerField()),
                ('amount', models.BigIntegerField()),
                ('legerEntryType', models.CharField(choices=[('SALE', 'Sale'), ('REFUND', 'Refund'), ('COMMISSION', 'Commission'), ('PAYOUT', 'Payout'), ('ADJUSTMENT', 'Adjustment')], max_length=10)),
                ('referenceID', models.CharField(db_index=True, max_length=600)),
            ],
        ),
    ]
